dist: focal
language: python

python:
  - 3.12

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate

script:
  - black --check .
  - flake8 --max-line-length=150 .
  - coverage run --source=swe1-app,polls manage.py test

after_script:
  - coveralls
  
deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_ID"
  secret_access_key: "$AWS_ACCESS_KEY"
  region: "us-west-2"
  app: "swe1-app"
  env: "swe1-app"
  bucket_name: elasticbeanstalk-us-west-2-156041445795
  on:
    repo: Jefferyl240/swe1-app
    branch: main
  skip_cleanup: 'true'
