language: python

python:
  - "3.8"
  - "3.9"
  - "3.10"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 --max-line-length=150.
  - coverage run manage.py test

after_script:
  - coveralls
